### ISSUE TITLE
Add trailingSlash

### ISSUE THREAD

**Issue by dubanoze** [Skycoder42/QtRestClient#1]
Hello.
How i can add trailingSlash to url?

**Comment by Skycoder42** [comment]
Trailing slashes are supported, but currently not made available via the restclient/class - which means you have to use [`QtRestClient::RequestBuilder::trailingSlash`](https://skycoder42.github.io/QtRestClient/class_qt_rest_client_1_1_request_builder.html#a7b899b2732870356087657ff0d398d59).

The builder itself is created internally, and can be customized by extending the [`QtRestClient::RestClient::builder`](https://skycoder42.github.io/QtRestClient/class_qt_rest_client_1_1_rest_client.html#adb823c9a8c96ce499c5dc4c81af2628c) or the [`QtRestClient::RestClass::builder`](https://skycoder42.github.io/QtRestClient/class_qt_rest_client_1_1_rest_class.html#afa0b24df3e788eefa415a4e8dd8e43c0) method.

If you, for example, want to globally enable trailing slashes for all requests, create a custom RestClient and extend it as follows:

```.cpp
class MyRestClient : public QtRestClient::RestClient
{
    Q_OBJECT

public:
    MyRestClient(QObject *parent = nullptr) : 
        RestClient(parent)
    {}

    QtRestClient::RequestBuilder MyClient::builder() const override {
        return RestClient::builder()
            .trailingSlash(true);
    }
};
```

The code for a `RestClass` is basically the same and would make that change only for the specific class instead of the whole client.

**Comment by dubanoze** [comment]
Thank you!
