### ISSUE TITLE
basic API access

### ISSUE THREAD

**Issue by fecub** [Skycoder42/QtRestClient#7]
Hello, I've read the examples and readme. My goal was to make an basic request. Example is given in the readme. But I get this error:

![restclient](https://user-images.githubusercontent.com/1592979/65320732-cbafed00-dba2-11e9-8104-78aa4cf67f08.png)

I've included this headers  in *.h 
```c++
#include <QtNetwork/QAuthenticator>
#include <QObject>
#include <QtRestClient>
#include <QtRestClient/GenericRestReply>
#include <QtRestClient/RestClient>
#include <QtRestClient/RestReply>
#include <QtRestClient/RestClass>
```

i am happy for any help.

p.s: i couldn't get it up and running yet, but i want to thank you for this great library :+1:

**Comment by Skycoder42** [comment]
If you examine the error message, you can see what the problem is:

> No know conversion from lambda to std::function<void(int, Post)>

Your lambda however uses `void(RestReply*, int, Post)` - which does not match up. The reply is not passed to the function, as it does not hold any viable information. Just leave it out as seen below. I just realized this is wrong in the README. I will correct that asap!

```
restClass->get<Post>("42")->onSucceeded([](int statusCode, Post data) { //calls: GET https://jsonplaceholder.typicode.com/posts/42
	//do whatever you want with the data
	qDebug() << data.id
			 << data.userId
			 << data.title
			 << data.body
});
```

Note: If you do need the reply, just store and and pass it via the lambda:
```
auto reply = restClass->get<Post>("42");
reply->onSucceeded([reply](int statusCode, Post data) {
	...
});
```

**Comment by fecub** [comment]
thanks a lot it worked, was a bit noobish from me :)
